backend:
  name: github
  repo: yuichkun/resonage-hp

media_folder: static/assets
public_folder: assets

collections:
  - name: news
    label: News
    folder: news
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }